server:
  port: ${SERVER_PORT:1234}

springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha

spring:
  application:
    name: resilience-poc

  cloud:
    azure:
      storage:
        blob:
          connectionString: ${CONNECTION_STRING:AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;}

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

