{
 "title": "Product Microservice Resilience",
 "description": "This dashboard contains stats about resilience metrics of Product MS.",
 "time": { "from": "2023-07-11T20:06:02.411Z", "to": "2023-07-11T20:07:28.257Z" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(resilience4j_circuitbreaker_state, instance)"
    }
   },
   {
    "name": "circuitbreaker_name",
    "label": "CircuitBreaker Name",
    "query": {
     "query": "label_values(resilience4j_circuitbreaker_state, name)"
    }
   },
   {
    "name": "retry_name",
    "label": "Retry Name",
    "query": {
     "query": "label_values(resilience4j_retry_calls_total, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "RateLimiter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of available permission",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(resilience4j_ratelimiter_available_permissions{name=\"backendImages\"})"
    }
   ]
  },
  { "title": "Circuit Breaker Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CircuitBreaker States",
   "type": "graph",
   "gridPos": { "h": 14, "w": 15, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_state{instance=~\"$instance\"}",
     "legendFormat": "{{ name }}: {{ state }}"
    }
   ]
  },
  {
   "title": "Total Number of Circuit Breaker",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state)"
    }
   ]
  },
  {
   "title": "Number of closed CircuitBreaker",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{state=\"closed\"})"
    }
   ]
  },
  {
   "title": "Number of open CircuitBreaker",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{state=~\"open|forced_open\"})"
    }
   ]
  },
  {
   "title": "Number of half_open CircuitBreaker",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{state=\"half_open\"})"
    }
   ]
  },
  { "title": "CircuitBreaker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "circuitbreaker_name" },
  {
   "title": "Failure Rate: $circuitbreaker_name",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 3, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_failure_rate{instance=~\"$instance\",name=~\"$circuitbreaker_name\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Call rate: $circuitbreaker_name",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Calls/sec" }
   ],
   "targets": [
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_seconds_count{instance=~\"$instance\",name=~\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind }} "
    },
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_total{instance=~\"$instance\",name=~\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind  }} "
    }
   ]
  },
  {
   "title": "Buffered calls: $circuitbreaker_name",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_buffered_calls{instance=~\"$instance\",name=~\"$circuitbreaker_name\"}",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "resilience4j_circuitbreaker_max_buffered_calls{instance=~\"$instance\",name=~\"$circuitbreaker_name\"}",
     "legendFormat": "maximum"
    }
   ]
  },
  {
   "title": "Average call durations",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "s", "label": "Average duration" }
   ],
   "targets": [
    {
     "expr": "increase(resilience4j_circuitbreaker_calls_seconds_sum{instance=~\"$instance\",name=~\"$circuitbreaker_name\"}[1m]) / increase(resilience4j_circuitbreaker_calls_seconds_count{instance=~\"$instance\",name=~\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "sum(increase(resilience4j_circuitbreaker_calls_seconds_sum{instance=~\"$instance\",name=~\"$circuitbreaker_name\"}[1m])) / sum(increase(resilience4j_circuitbreaker_calls_seconds_count{instance=~\"$instance\",name=~\"$circuitbreaker_name\"}[1m]))",
     "legendFormat": "total "
    }
   ]
  },
  { "title": "Retry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 }, "repeat": "retry_name" },
  {
   "title": "Rate retryable calls: $retry_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short", "label": "Number of calls" }
   ],
   "targets": [
    {
     "expr": "rate(resilience4j_retry_calls_total{application=~\"$application\",name=~\"$retry_name\",}[1m])",
     "legendFormat": "{{ kind }}"
    }
   ]
  }
 ]
}