version: '3.9'
services:

  image-uploader:
    build: .
    container_name: image-uploader
    ports:
      - "1234:1234"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"